// ⚠️ PL-009: ru/en translations are AI-generated / UNVERIFIED.
// Must be reviewed by a professional translator before beta launch.
// Uzbek Cyrillic text is transcribed from the government СТАНДАРТ PDF (ЛОЙИҲА/DRAFT, Tashkent 2025).
//
// levelDescriptions keys are in SOFTWARE direction: 4 = best, 0 = worst.
// softwareScore = 4 − printedScore (scoring inversion locked in IRR-DECISIONS.md).
// The printed standard has 0 = best; software inverts this for intuitive rising-score progress.
//
// scoringType:
//   'ability'       — criteria 1–13: ability / independence
//   'frequency'     — criteria 14–15: frequency of problem behavior
//   'participation' — criteria 16–17: degree of participation
//
// isHearingSpecific: true only for criterion 9 (hearing/sign communication).
// Per OQ-1 decision: criterion 9 is scored for ALL children. Max = 68. isHearingSpecific
// is metadata for display (shown with special label) — NOT an exclusion from scoring.

export const ASSESSMENT_CRITERIA = [
  {
    code: 'SELF_FEEDING',
    sortOrder: 1,
    textUz: 'Мустақил овқатланадими? (шу жумладан овқатланиш ва ичиш)',
    textRu: 'Может ли питаться самостоятельно? (включая приём пищи и питьё)',
    textEn: 'Can eat independently? (including eating and drinking)',
    isHearingSpecific: false,
    scoringType: 'ability',
    isActive: true,
    levelDescriptions: {
      '4': { uz: 'Мустақил бажаради', ru: 'Выполняет самостоятельно', en: 'Does independently' },
      '3': { uz: 'Деярли ҳеч қандай ёрдамсиз', ru: 'Почти без посторонней помощи', en: 'Almost without help' },
      '2': { uz: 'Бироз ёрдам билан ёки баъзан', ru: 'С небольшой помощью или иногда', en: 'With some help or sometimes' },
      '1': { uz: 'Бошқалар ёрдамида бажаради', ru: 'Выполняет с помощью других', en: 'Does with others\' help' },
      '0': { uz: 'Бажара олмайди', ru: 'Не может выполнить', en: 'Cannot do it' },
    },
  },
  {
    code: 'PERSONAL_HYGIENE',
    sortOrder: 2,
    textUz: 'Шахсий гигиенага риоя қилади (шу жумладан ювиниш, ванна қабул қилиш ва тишларни тозалаш)',
    textRu: 'Соблюдает личную гигиену (включая умывание, купание и чистку зубов)',
    textEn: 'Maintains personal hygiene (including washing, bathing, brushing teeth)',
    isHearingSpecific: false,
    scoringType: 'ability',
    isActive: true,
    levelDescriptions: {
      '4': { uz: 'Мустақил бажаради', ru: 'Выполняет самостоятельно', en: 'Does independently' },
      '3': { uz: 'Деярли ҳеч қандай ёрдамсиз', ru: 'Почти без посторонней помощи', en: 'Almost without help' },
      '2': { uz: 'Бироз ёрдам билан ёки баъзан', ru: 'С небольшой помощью или иногда', en: 'With some help or sometimes' },
      '1': { uz: 'Бошқалар ёрдамида бажаради', ru: 'Выполняет с помощью других', en: 'Does with others\' help' },
      '0': { uz: 'Бажара олмайди', ru: 'Не может выполнить', en: 'Cannot do it' },
    },
  },
  {
    code: 'DRESSING',
    sortOrder: 3,
    textUz: 'Кийинади ва ечинади',
    textRu: 'Одевается и раздевается',
    textEn: 'Gets dressed and undressed',
    isHearingSpecific: false,
    scoringType: 'ability',
    isActive: true,
    levelDescriptions: {
      '4': { uz: 'Мустақил бажаради', ru: 'Выполняет самостоятельно', en: 'Does independently' },
      '3': { uz: 'Деярли ҳеч қандай ёрдамсиз', ru: 'Почти без посторонней помощи', en: 'Almost without help' },
      '2': { uz: 'Бироз ёрдам билан ёки баъзан', ru: 'С небольшой помощью или иногда', en: 'With some help or sometimes' },
      '1': { uz: 'Бошқалар ёрдамида бажаради', ru: 'Выполняет с помощью других', en: 'Does with others\' help' },
      '0': { uz: 'Бажара олмайди', ru: 'Не может выполнить', en: 'Cannot do it' },
    },
  },
  {
    code: 'TOILET_USE',
    sortOrder: 4,
    textUz: 'Горшокдан фойдаланади (ҳожатхонага боради)',
    textRu: 'Пользуется туалетом (ходит в туалет)',
    textEn: 'Uses toilet (goes to toilet)',
    isHearingSpecific: false,
    scoringType: 'ability',
    isActive: true,
    levelDescriptions: {
      '4': { uz: 'Мустақил бажаради', ru: 'Выполняет самостоятельно', en: 'Does independently' },
      '3': { uz: 'Деярли ҳеч қандай ёрдамсиз', ru: 'Почти без посторонней помощи', en: 'Almost without help' },
      '2': { uz: 'Бироз ёрдам билан ёки баъзан', ru: 'С небольшой помощью или иногда', en: 'With some help or sometimes' },
      '1': { uz: 'Бошқалар ёрдамида бажаради', ru: 'Выполняет с помощью других', en: 'Does with others\' help' },
      '0': { uz: 'Бажара олмайди', ru: 'Не может выполнить', en: 'Cannot do it' },
    },
  },
  {
    code: 'BOWEL_CONTROL',
    sortOrder: 5,
    textUz: 'Нажас ва сийдикни ушлаб туришни бошқаради',
    textRu: 'Контролирует мочеиспускание и дефекацию',
    textEn: 'Controls bowel and bladder',
    isHearingSpecific: false,
    scoringType: 'ability',
    isActive: true,
    levelDescriptions: {
      '4': { uz: 'Иккаласини ҳам бошқаради', ru: 'Контролирует оба', en: 'Controls both' },
      '3': { uz: 'Сийдикни ушлаб туришни деярли эплайди, нажасни ушлаб туради', ru: 'Почти контролирует мочеиспускание, контролирует дефекацию', en: 'Almost controls urination, controls bowel' },
      '2': { uz: 'Кўпинча сийдикни ушлаб туришни бошқара олмайди', ru: 'Часто не может контролировать мочеиспускание', en: 'Often cannot control urination' },
      '1': { uz: 'Сийдикни ушлаб тура олмайди', ru: 'Не может контролировать мочеиспускание', en: 'Cannot control urination' },
      '0': { uz: 'Нажасни ушлаб тура олмайди', ru: 'Не может контролировать дефекацию', en: 'Cannot control bowel movements' },
    },
  },
  {
    code: 'SIMPLE_INSTRUCTIONS',
    sortOrder: 6,
    textUz: 'Оддий кўрсатмаларни тушунади',
    textRu: 'Понимает простые инструкции',
    textEn: 'Understands simple instructions',
    isHearingSpecific: false,
    scoringType: 'ability',
    isActive: true,
    levelDescriptions: {
      '4': { uz: 'Осон', ru: 'Легко', en: 'Easily' },
      '3': { uz: 'Озгина қийинчилик билан', ru: 'С небольшим затруднением', en: 'With slight difficulty' },
      '2': { uz: 'Баъзи қийинчиликлар билан', ru: 'С некоторыми затруднениями', en: 'With some difficulty' },
      '1': { uz: 'Катта қийинчиликлар билан', ru: 'С большими затруднениями', en: 'With great difficulty' },
      '0': { uz: 'Тушунмайди', ru: 'Не понимает', en: 'Does not understand' },
    },
  },
  {
    code: 'EXPRESS_NEEDS',
    sortOrder: 7,
    textUz: 'Ўз эҳтиёжларини билдиради (сув сўрайди?)',
    textRu: 'Выражает свои потребности (просит воду?)',
    textEn: 'Expresses own needs (asks for water?)',
    isHearingSpecific: false,
    scoringType: 'ability',
    isActive: true,
    levelDescriptions: {
      '4': { uz: 'Осон', ru: 'Легко', en: 'Easily' },
      '3': { uz: 'Озгина қийинчилик билан', ru: 'С небольшим затруднением', en: 'With slight difficulty' },
      '2': { uz: 'Баъзи қийинчиликлар билан', ru: 'С некоторыми затруднениями', en: 'With some difficulty' },
      '1': { uz: 'Катта қийинчиликлар билан', ru: 'С большими затруднениями', en: 'With great difficulty' },
      '0': { uz: 'Тушунмайди', ru: 'Не может выразить', en: 'Cannot express' },
    },
  },
  {
    code: 'VERBAL_COMMUNICATION',
    sortOrder: 8,
    textUz: 'Гаплаша олади',
    textRu: 'Может говорить / общаться вербально',
    textEn: 'Can speak / communicate verbally',
    isHearingSpecific: false,
    scoringType: 'ability',
    isActive: true,
    levelDescriptions: {
      '4': { uz: 'Бемалол', ru: 'Свободно', en: 'Freely' },
      '3': { uz: 'Деярли эркин', ru: 'Почти свободно', en: 'Almost freely' },
      '2': { uz: 'Бироз қийналади', ru: 'Немного затрудняется', en: 'Has some difficulty' },
      '1': { uz: 'Зўрға', ru: 'С трудом', en: 'With great difficulty' },
      '0': { uz: 'Гаплаша олмайди', ru: 'Не может говорить', en: 'Cannot speak' },
    },
  },
  {
    code: 'SIGN_COMMUNICATION',
    sortOrder: 9,
    textUz: 'Мулоқот учун қўлланиладиган ҳаракат ва ишораларни тушунадими? Эшитиш қобилияти чекланган болалар учун',
    textRu: 'Понимает ли движения и знаки, используемые для общения? Для детей с нарушением слуха',
    textEn: 'Understands movements and signs used for communication? For children with hearing disabilities',
    isHearingSpecific: true,
    scoringType: 'ability',
    isActive: true,
    levelDescriptions: {
      '4': { uz: 'Осон тушунади', ru: 'Легко понимает', en: 'Understands easily' },
      '3': { uz: 'Деярли қийналмайди', ru: 'Почти без затруднений', en: 'Almost without difficulty' },
      '2': { uz: 'Бироз қийналади', ru: 'Немного затрудняется', en: 'Has some difficulty' },
      '1': { uz: 'Зўрға', ru: 'С трудом', en: 'With great difficulty' },
      '0': { uz: 'Тушунмайди', ru: 'Не понимает', en: 'Does not understand' },
    },
  },
  {
    code: 'SIT_INDEPENDENTLY',
    sortOrder: 10,
    textUz: 'Мустақил ўтиради',
    textRu: 'Сидит самостоятельно',
    textEn: 'Can sit independently',
    isHearingSpecific: false,
    scoringType: 'ability',
    isActive: true,
    levelDescriptions: {
      '4': { uz: 'Мустақил ўтиради', ru: 'Сидит самостоятельно', en: 'Sits independently' },
      '3': { uz: 'Деярли ёрдамсиз мумкин', ru: 'Почти без помощи', en: 'Almost without help' },
      '2': { uz: 'Бироз ёрдам билан ёки баъзан', ru: 'С небольшой помощью или иногда', en: 'With some help or sometimes' },
      '1': { uz: 'Бошқаларнинг ёрдами билан ўтиради', ru: 'Сидит с помощью других', en: 'Sits with others\' help' },
      '0': { uz: 'Ўтирмайди', ru: 'Не может сидеть', en: 'Cannot sit' },
    },
  },
  {
    code: 'STAND',
    sortOrder: 11,
    textUz: 'Тура олади, жумладан ўтирган ҳолатдан ҳам тура олади',
    textRu: 'Может стоять, в том числе вставать из положения сидя',
    textEn: 'Can stand, including from seated position',
    isHearingSpecific: false,
    scoringType: 'ability',
    isActive: true,
    levelDescriptions: {
      '4': { uz: 'Мустақил туради', ru: 'Стоит самостоятельно', en: 'Stands independently' },
      '3': { uz: 'Деярли ёрдамсиз', ru: 'Почти без помощи', en: 'Almost without help' },
      '2': { uz: 'Бироз ёрдам билан ёки баъзан', ru: 'С небольшой помощью или иногда', en: 'With some help or sometimes' },
      '1': { uz: 'Бошқаларнинг ёрдами билан туради', ru: 'Стоит с помощью других', en: 'Stands with others\' help' },
      '0': { uz: 'Тура олмайди', ru: 'Не может стоять', en: 'Cannot stand' },
    },
  },
  {
    code: 'CLIMB_STAIRS',
    sortOrder: 12,
    textUz: 'Камида 10 та зинапоядан чиқади',
    textRu: 'Поднимается минимум на 10 ступеней',
    textEn: 'Climbs at least 10 stairs',
    isHearingSpecific: false,
    scoringType: 'ability',
    isActive: true,
    levelDescriptions: {
      '4': { uz: 'Мустақил равишда ва махсус мосламаларсиз', ru: 'Самостоятельно и без специальных приспособлений', en: 'Independently and without special aids' },
      '3': { uz: 'Деярли ёрдамсиз', ru: 'Почти без помощи', en: 'Almost without help' },
      '2': { uz: 'Бироз ёрдам билан ёки баъзан', ru: 'С небольшой помощью или иногда', en: 'With some help or sometimes' },
      '1': { uz: 'Бошқаларнинг ёрдами билан чиқади', ru: 'Поднимается с помощью других', en: 'Climbs with others\' help' },
      '0': { uz: 'Чиқмайди', ru: 'Не может подняться', en: 'Cannot climb' },
    },
  },
  {
    code: 'INDOOR_MOBILITY',
    sortOrder: 13,
    textUz: 'Уй ичида юриш, эмаклаб юриш ва аравачадан фойдаланган ҳолда ҳаракатлана олади',
    textRu: 'Может передвигаться внутри помещения пешком, ползком или на коляске',
    textEn: 'Can move inside the house by walking, crawling, or using a wheelchair',
    isHearingSpecific: false,
    scoringType: 'ability',
    isActive: true,
    levelDescriptions: {
      '4': { uz: 'Мустақил равишда ва махсус мосламаларсиз', ru: 'Самостоятельно и без специальных приспособлений', en: 'Independently and without special aids' },
      '3': { uz: 'Деярли ёрдамсиз', ru: 'Почти без помощи', en: 'Almost without help' },
      '2': { uz: 'Бироз ёрдам билан ёки баъзан', ru: 'С небольшой помощью или иногда', en: 'With some help or sometimes' },
      '1': { uz: 'Бошқаларнинг ёрдами билан ҳаракатланади', ru: 'Передвигается с помощью других', en: 'Moves with others\' help' },
      '0': { uz: 'Ҳаракатланмайди', ru: 'Не может передвигаться', en: 'Cannot move' },
    },
  },
  {
    code: 'UNUSUAL_BEHAVIOR',
    sortOrder: 14,
    textUz: 'Ўзини ноодатий тутади',
    textRu: 'Проявляет необычное поведение',
    textEn: 'Shows unusual behavior',
    isHearingSpecific: false,
    scoringType: 'frequency',
    isActive: true,
    levelDescriptions: {
      '4': { uz: 'Ҳеч қачон', ru: 'Никогда', en: 'Never' },
      '3': { uz: 'Ха, лекин камдан-кам (ойига бир марта ёки камроқ)', ru: 'Да, но редко (раз в месяц или реже)', en: 'Yes, but rarely (once a month or less)' },
      '2': { uz: 'Ха, баъзида (ҳафтада бир марта)', ru: 'Да, иногда (раз в неделю)', en: 'Yes, sometimes (once a week)' },
      '1': { uz: 'Ха, тез-тез (ҳар куни)', ru: 'Да, часто (каждый день)', en: 'Yes, often (every day)' },
      '0': { uz: 'Ха мунтазам (кунига бир неча марта)', ru: 'Да, регулярно (несколько раз в день)', en: 'Yes, regularly (several times a day)' },
    },
  },
  {
    code: 'SEIZURES',
    sortOrder: 15,
    textUz: 'Тутқаноқ ҳуружлари',
    textRu: 'Судорожные припадки',
    textEn: 'Seizures / convulsions',
    isHearingSpecific: false,
    scoringType: 'frequency',
    isActive: true,
    levelDescriptions: {
      '4': { uz: 'Ҳеч қачон', ru: 'Никогда', en: 'Never' },
      '3': { uz: 'Ха, йилига 3 мартадан кам', ru: 'Да, менее 3 раз в год', en: 'Yes, fewer than 3 times a year' },
      '2': { uz: 'Ха, тахминан ойига бир марта', ru: 'Да, примерно раз в месяц', en: 'Yes, approximately once a month' },
      '1': { uz: 'Ха, тахминан ҳафтада бир марта камдан-кам', ru: 'Да, примерно раз в неделю (редко)', en: 'Yes, approximately once a week (rarely)' },
      '0': { uz: 'Ха, ҳар куни', ru: 'Да, каждый день', en: 'Yes, every day' },
    },
  },
  {
    code: 'FAMILY_PARTICIPATION',
    sortOrder: 16,
    textUz: 'Оилавий ҳаётда иштирок этадими?',
    textRu: 'Участвует в семейной жизни?',
    textEn: 'Participates in family life?',
    isHearingSpecific: false,
    scoringType: 'participation',
    isActive: true,
    levelDescriptions: {
      '4': { uz: 'Ха, оиланинг бошқа аъзолари қатори тенг равишда', ru: 'Да, наравне с другими членами семьи', en: 'Yes, equally with other family members' },
      '3': { uz: 'Ха, оилавий ҳаётда тез-тез иштирок этади', ru: 'Да, часто участвует в семейной жизни', en: 'Yes, frequently participates in family life' },
      '2': { uz: 'Ха, баъзан', ru: 'Да, иногда', en: 'Yes, sometimes' },
      '1': { uz: 'Камдан-кам иштирок этади', ru: 'Редко участвует', en: 'Rarely participates' },
      '0': { uz: 'Умуман иштирок этмайди', ru: 'Совсем не участвует', en: 'Does not participate at all' },
    },
  },
  {
    code: 'HOUSEHOLD_TASKS',
    sortOrder: 17,
    textUz: 'Уй ишларини бажарадими?',
    textRu: 'Выполняет ли домашние обязанности?',
    textEn: 'Does household tasks?',
    isHearingSpecific: false,
    scoringType: 'participation',
    isActive: true,
    levelDescriptions: {
      '4': { uz: 'Ха, барча ишларни бажаради', ru: 'Да, выполняет все обязанности', en: 'Yes, does all tasks' },
      '3': { uz: 'Кўпини бажаради, лекин ҳаммасини эмас', ru: 'Выполняет большинство, но не все', en: 'Does most but not all' },
      '2': { uz: 'Бир қатор вазифаларни бажаради', ru: 'Выполняет ряд обязанностей', en: 'Does some tasks' },
      '1': { uz: 'Баъзи ишларни бажаради', ru: 'Выполняет некоторые обязанности', en: 'Does only a few tasks' },
      '0': { uz: 'Бажармайди', ru: 'Не выполняет', en: 'Does not do any tasks' },
    },
  },
];

export const CRITERIA_COUNT = ASSESSMENT_CRITERIA.length; // must be 17
export const MAX_SCORE = CRITERIA_COUNT * 4; // 68 — all children including criterion 9 (OQ-1)
